/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 PurpleMonkey FM-1 contributors (on ChoralRoot FM-1, a fork of Felucca by Leo Kuroshita,
 * Hügelton Instruments) */
/* PURPLEMONKEY FM-1: one compilation unit (the HAL is header-only), as ChoralRoot's choralroot.c is (docs/
 * PURPLEMONKEY.md, Architecture). Felucca's platform as ChoralRoot carries it: boot, the boot guard and SAFE MODE's
 * counting (main.c, cr_bootguard.h), the LCD, the key / button / encoder scan, the audio ISR (audio.c), the voices
 * and the FX (voice.c, fx.c), USB MIDI (usb.c), the flash driver and the update entry (storage_hw.c, ota.c).
 * ChoralRoot's instrument (cr_*.c: its engine, screens, UI, sounds, stores, backup) is not in this unit;
 * PurpleMonkey's is:
 *   pm_engine.c   the musical engine: keys, clock, pattern, repeats, phrase (plain C, host tested)
 *   pm_out.c      the engine in the audio ISR, on part 0 (FM6) and on its own drum voices (pm_drum_synth.c: SLOOP's
 *                 synthesised drums); events_block and the few names of Felucca's sequencer the kept files call
 *   pm_sound.c    the pets' FM6 patches and the two sound macros
 *   pm_ui.c       the panel, the LEDs, the screen
 *   pm_shim.c     what main.c (kept as it is but for the splash) calls of Felucca's dropped UI
 * Nothing is stored: no settings, no user sounds, no save or erase anywhere (storage.c, the stores and the settings
 * record are not in the unit; the flash driver stays for the update only).
 *
 * Host check (no device toolchain): cc -fsyntax-only -w -Ibuild/gen -Ifirmware/src -Ifirmware/hal
 * firmware/src/purplemonkey.c. The device build is tools/build.py (./build.sh) with this file as the unit. */

/* ---------------------------------------------------- build options --- */
#ifndef FELUCCA_FLASH
#define FELUCCA_FLASH 1          /* the flash driver: the update needs it (nothing else writes the flash) */
#endif
#ifndef FELUCCA_OTA
#define FELUCCA_OTA 1            /* M-UPGRADE update entry; needs FELUCCA_FLASH */
#endif
#ifndef FELUCCA_OTA_DRYRUN
#define FELUCCA_OTA_DRYRUN 0
#endif
#ifndef FELUCCA_CDC
#define FELUCCA_CDC 0            /* no USB serial console (console.c prints ChoralRoot's state) */
#endif
#ifndef FELUCCA_UAC
#define FELUCCA_UAC 1            /* USB audio recording (Melodee's, docs/USB-AUDIO.md): the master on channels 1-2, the
                                  * synth part on 3-4 (5-6: ChoralRoot's BASS pair, silent here) */
#endif
#ifndef FELUCCA_UART
#define FELUCCA_UART 1           /* TRS MIDI IN on UART1 / PH8: a bigger keyboard plays the sounds (pm_out.c) */
#endif
#define FELUCCA_SLICE 0          /* FM6 is the synth; the drums are pm_drum_synth.c's. No other engine is offered */
#define FELUCCA_SLICER 0         /* (the engines Felucca always builds stay in the image, unused: engines.c) */
#define FELUCCA_FM4 0
#define FELUCCA_SAMPLE 0
#define FELUCCA_GRAIN 0
#define FELUCCA_DRUM 0
#define FELUCCA_SEQ 0            /* no Felucca sequencer: pm_out.c has events_block */
#define FELUCCA_VA 0
#define FELUCCA_CZ 0
#ifndef FM6_POLY
#define FM6_POLY 8               /* FM6's voices (ChoralRoot's cap; docs/PURPLEMONKEY.md, Budgets) */
#endif
#define FELUCCA_ICONS 0
#define FELUCCA_KEYCAPS 0
#define PM_UBOOT_HOME 1          /* main.c: update mode is OCT- + OCT+ + HOME held 5 s (not the two OCT buttons alone) */
#ifndef FELUCCA_ID
#define FELUCCA_ID "FM-1_927"    /* package identity (build.py: the .fwsc marker string) */
#endif
#ifndef FELUCCA_VERSION
#define FELUCCA_VERSION "PurpleMonkey 0.1-dev"
#endif
#if FELUCCA_OTA && !FELUCCA_FLASH
#error "FELUCCA_OTA needs FELUCCA_FLASH"
#endif

#if defined(__APPLE__)            /* the host syntax check only: Mach-O has no ELF sections (.noinit, .pool) */
#define __attribute__(x)
#endif

/* ------------------------------------------------------------- HAL --- */
#include <stdint.h>
#include "fm1_time.h"
#include "fm1_sys.h"
#include "fm1_irq.h"
#include "fm1_guard.h"
#include "fm1_input.h"
#include "fm1_timer.h"
#include "fm1_audio.h"
#include "fm1_adc.h"
#include "fm1_lcd_hw.h"
#include "felucca_tables.h"      /* generated by build.py (tools/gen_tables.py) */

/* ----------------------------------------------------- base, display --- */
#include "libc.c"
#include "lcd.c"
#include "gfx.c"

/* ----------------------------------------------------------- sound --- */
#include "core.h"
#include "engines.c"             /* dsp.c, the eng_*.c files */
#include "params.c"
#include "mod.c"
#include "voice.c"
#include "slicer.c"
#define mix_block fx_mix_block   /* fx.c's mix; audio.c gets PurpleMonkey's (below) */
#include "fx.c"
#undef mix_block

/* ------------------------------------------------------------ MIDI --- */
#include "usb.c"
#if FELUCCA_UART
#include "midi_uart.c"
#endif

/* ----------------------------------------------- the PurpleMonkey engine --- */
#include "pm_engine.c"
#include "pm_out.c"              /* the engine on part 0 and the drums; events_block */
static void mix_block(int32_t *out, uint32_t n)   /* the audio ISR's block: the engine first, then the mix */
{
    pm_audio_block(n);
#if FELUCCA_UAC
    ua_stage_on = ua.cap_alt && !USB_CDC_ON;     /* the computer records: fx.c stages the block's capture frames */
#endif
    fx_mix_block(out, n);
#if FELUCCA_UAC
    if (ua_stage_on) {                           /* the master pair (as choralroot.c's shim) */
        uint32_t i;
        for (i = 0; i < n; i++) {
            ua_stage[i * UA_CAP_CHANNELS] = ua_sat(out[2u * i]);
            ua_stage[i * UA_CAP_CHANNELS + 1u] = ua_sat(out[2u * i + 1u]);
        }
    }
#endif
}
#include "audio.c"

/* -------------------------------------------------------------- UI --- */
#include "panel.c"
#if FELUCCA_FLASH
#include "fm1_flash.h"
#include "storage_hw.c"          /* the flash driver (the update's; no store is read or written) */
#endif
#include "pm_sound.c"
#include "pm_ui.c"
#include "pm_shim.c"             /* what main.c calls of Felucca's dropped UI */

/* ----------------------------------------------------------- update --- */
#if FELUCCA_OTA
#include "ota.c"
#include "ota_hw.c"
#endif
#include "pm_info.c"             /* main.c's ed_service: the installers' "which firmware is this?" */
#include "main.c"
