#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generated scripts for the PurpleMonkey emulator's acceptance (tools/emu/test_pm.sh): the long ones.

  tools/emu/pm_scripts.py OUTDIR

  pm_keys.txt   every one of the 27 keys, in SYNTH and in DRUMS, with the beat off (each press must sound, and
                light its LED) and with the beat on
  pm_mash.txt   a small child at the panel: 60 s of random keys (up to ten at once, some held for seconds), every
                button, every knob; then hands off for 6 s (fixed seed: the same every run)
  pm_load.txt   the most this firmware can be asked for at once: the sustained sound with the keys full, its phrase
                running, the busiest beat at the fastest tempo, knobs turning, pets changing
"""
import random
import sys
from pathlib import Path

N = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
KEYS = [f"{N[(53 + k) % 12]}{(53 + k) // 12 - 1}" for k in range(27)]
BUTTONS = ["FX", "SEL", "ENV", "LFO", "EDIT", "GLO", "HOME", "SAVE", "ARP", "SEQ", "PLAY", "REC", "OCT-", "OCT+"]
KNOBS = ["SELECT", "ALGORITHM", "PRESETS", "KNOB1", "KNOB2", "KNOB3", "KNOB4"]


def keys():
    L = ["# generated by tools/emu/pm_scripts.py", "wait 400", "expect silence"]
    for mode, btn in (("SYNTH", "SEL"), ("DRUMS", "FX")):
        L += [f"# {mode}, the beat off", f"btn {btn}", "wait 600"]
        for k in KEYS:
            L += [f"btn {k} down", "wait 50", f"expect led {k} on", f"btn {k} up", "wait 70", "expect sound",
                  f"expect led {k} dim"]
        L += ["wait 3000"]
    L += ["btn PLAY", "wait 100"]
    for mode, btn in (("SYNTH", "SEL"), ("DRUMS", "FX")):
        L += [f"# {mode}, the beat on", f"btn {btn}", "wait 300"]
        for k in KEYS:
            L += [f"btn {k} down", "wait 50", f"expect led {k} on", f"btn {k} up", "wait 70", "expect sound"]
    L += ["btn PLAY", "wait 6000", "dump"]
    return L


def mash(seed=27, secs=60):
    r = random.Random(seed)
    L = ["# generated by tools/emu/pm_scripts.py", "wait 300"]
    down, t, beat = set(), 300, False
    while t < secs * 1000:
        x = r.random()
        if x < 0.50:
            k = r.choice(KEYS)
            if k in down or len(down) >= 10:
                k = r.choice(sorted(down)) if down else k
                L.append(f"btn {k} up")
                down.discard(k)
            else:
                L.append(f"btn {k} down")
                down.add(k)
        elif x < 0.60:
            b = r.choice(BUTTONS)
            beat ^= b == "PLAY"                  # (PLAY toggles the beat)
            L.append(f"btn {b} {r.choice((30, 80, 200))}")
            t += 80
        elif x < 0.72:
            L.append(f"knob {r.choice(KNOBS)} {r.choice((-3, -2, -1, 1, 2, 3)):+d}")
        elif x < 0.75:
            for k in r.sample(KEYS, 6):          # a flat hand
                if k not in down:
                    L.append(f"btn {k} down")
                    down.add(k)
        d = r.choice((5, 10, 20, 40, 80, 150, 400, 1200) if x > 0.3 else (5, 10, 20))
        L.append(f"wait {d}")
        t += d
    for k in sorted(down):
        L.append(f"btn {k} up")
    L += ["wait 100", "shot build/emu/pm/mash_end.ppm", "btn HOME", "wait 100"]
    if beat:
        L += ["expect led PLAY on", "btn PLAY", "wait 100"]
    L += ["expect led PLAY dim", "wait 6000", "dump"]
    return L


def load():
    L = ["# generated by tools/emu/pm_scripts.py", "wait 300", "knob SELECT +2", "wait 100",   # the llama: it sustains
         "knob KNOB1 +8", "knob KNOB2 +4", "knob ALGORITHM +8", "knob PRESETS +8", "btn PLAY", "wait 200"]
    for k in KEYS[::2]:
        L += [f"btn {k} down", "wait 30"]
    L += ["wait 3000", "dump"]
    for i in range(12):
        L += [f"knob SELECT {'+1' if i % 2 else '-1'}", "knob KNOB3 +1", "knob KNOB4 -1", "wait 250"]
        L += [f"btn {KEYS[(i * 5) % 27]} down", "wait 120", f"btn {KEYS[(i * 5) % 27]} up", "wait 120"]
    L += ["btn FX", "wait 100"]
    for k in KEYS[::2]:
        L += [f"btn {k} up", "wait 5"]
    for k in KEYS[1::2]:                         # DRUMS: thirteen keys repeating over the busiest beat
        L += [f"btn {k} down", "wait 20"]
    L += ["wait 5000", "dump", "shot build/emu/pm/load.ppm"]
    for k in KEYS[1::2]:
        L += [f"btn {k} up"]
    L += ["btn PLAY", "wait 6000", "dump"]
    return L


if __name__ == "__main__":
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    for name, lines in (("pm_keys", keys()), ("pm_mash", mash()), ("pm_load", load())):
        (out / f"{name}.txt").write_text("\n".join(lines) + "\n")
