#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 PurpleMonkey FM-1 contributors
"""PurpleMonkey's FM6 sounds, one per pet (firmware/src/pm_sound.c) -> a C header of packed 128-byte voices.

  tools/gen_pm_patches.py OUT.h

PurpleMonkey's own patches, written here as operator settings with gen_fm6_patches.py's helpers (no factory ROM
data of any instrument). Each is voiced for small hands and a small speaker: an instant attack that says "you
pressed a key", a mellow body (modulators that die away quickly, so a held or repeated note stays soft), nothing
harsh when eight sound at once. BRIGHT (PRESETS) moves the modulators' level around what is written here, LENGTH
(ALGORITHM) the envelopes' decay and release rates (pm_sound.c).
Algorithm 5 = three pairs (1<-2, 3<-4, 5<-6 with the feedback); 32 = six carriers.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from gen_fm6_patches import op, voice, pack  # noqa: E402

PETS = [
    # MONKEY: a round thumb-piano pluck with a little bass in it
    ("MONKEY", voice("PM KALIMBA", 5, [
        op(r=(99, 46, 32, 38), l=(99, 62, 0, 0), ol=99, kvs=2, rs=2),
        op(r=(99, 68, 44, 50), l=(99, 34, 0, 0), ol=66, fc=1, kvs=4, rs=3),
        op(r=(99, 54, 36, 40), l=(99, 40, 0, 0), ol=88, fc=2, kvs=2, rs=3, det=8),
        op(r=(99, 80, 60, 60), l=(99, 0, 0, 0), ol=58, fc=7, kvs=5, rs=4),
        op(r=(99, 40, 30, 36), l=(99, 70, 0, 0), ol=86, fc=0, kvs=1, rs=1),
        op(r=(99, 60, 40, 46), l=(99, 30, 0, 0), ol=48, fc=1, kvs=3)],
        fb=2)),
    # CAT: its xylophone: a wooden tock on a short warm note
    ("CAT", voice("PM XYLO", 5, [
        op(r=(99, 48, 35, 40), l=(99, 64, 0, 0), ol=99, kvs=2, rs=3),
        op(r=(99, 72, 52, 56), l=(99, 26, 0, 0), ol=70, fc=4, kvs=4, rs=3),
        op(r=(99, 52, 37, 42), l=(99, 50, 0, 0), ol=90, kvs=2, rs=3, det=8),
        op(r=(99, 78, 58, 60), l=(99, 0, 0, 0), ol=60, fc=10, kvs=5, rs=4),
        op(r=(99, 42, 32, 38), l=(99, 60, 0, 0), ol=80, fc=0, kvs=1, rs=2),
        op(r=(99, 86, 70, 70), l=(99, 0, 0, 0), ol=44, fc=3, kvs=3)],
        fb=1)),
    # DOG: a music box: a soft bell that rings on a little
    ("DOG", voice("PM BELLBOX", 5, [
        op(r=(99, 40, 28, 36), l=(99, 72, 0, 0), ol=98, kvs=2, rs=2),
        op(r=(99, 50, 34, 40), l=(99, 50, 0, 0), ol=62, fc=3, ff=17, kvs=3, rs=2),
        op(r=(99, 44, 30, 38), l=(99, 60, 0, 0), ol=86, fc=2, kvs=2, rs=2, det=8),
        op(r=(99, 60, 40, 46), l=(99, 30, 0, 0), ol=54, fc=7, kvs=4, rs=3),
        op(r=(99, 50, 34, 40), l=(99, 40, 0, 0), ol=78, fc=4, det=6, kvs=2, rs=3),
        op(r=(99, 70, 50, 60), l=(99, 0, 0, 0), ol=46, fc=9, kvs=3)],
        fb=0)),
    # LLAMA: a breathy pipe that holds for as long as the key does
    ("LLAMA", voice("PM PIPES", 5, [
        op(r=(72, 30, 24, 46), l=(99, 92, 88, 0), ol=98, kvs=1),
        op(r=(80, 50, 30, 50), l=(99, 60, 44, 0), ol=52, fc=1, kvs=2),
        op(r=(66, 30, 24, 44), l=(99, 90, 84, 0), ol=86, fc=2, kvs=1, det=8),
        op(r=(90, 60, 30, 50), l=(99, 40, 30, 0), ol=44, fc=2, kvs=2),
        op(r=(60, 28, 22, 42), l=(99, 94, 90, 0), ol=88, fc=1, det=6, kvs=1),
        op(r=(99, 70, 40, 50), l=(99, 30, 20, 0), ol=50, fc=3, kvs=3)],
        fb=2, lfs=30, lfd=40, lpmd=6, lfw=4, lpms=2)),
]


def main(path):
    L = ["/* generated by tools/gen_pm_patches.py: PurpleMonkey's FM6 voices (packed), in PM_MONKEY .. PM_LLAMA order */",
         "#pragma once", f"static const uint8_t PM_FM6[{len(PETS)}][128] = {{"]
    for name, v in PETS:
        L.append("    {" + ", ".join(str(x) for x in pack(v)) + f"}},   /* {name} */")
    L.append("};")
    Path(path).write_text("\n".join(L) + "\n")
    print(f"pm patches: {len(PETS)} -> {path}")


if __name__ == "__main__":
    main(sys.argv[1])
